// clients/web-app/src/components/chat/MessageBubble.vue
<script setup lang="ts">
import type { MessageItem } from '@/composables/useChatStream';
import StreamingText from './StreamingText.vue';
import ToolCallCard from './ToolCallCard.vue';
import MediaPreview from './MediaPreview.vue';
defineProps<{ message: MessageItem }>();
</script>

<template>
  <div v-if="message.kind === 'user'" class="row right">
    <div class="bubble user">
      <div v-if="message.media?.length" class="strip">
        <MediaPreview v-for="m in message.media" :key="m.id" :media="m" />
      </div>
      <div v-if="message.text">{{ message.text }}</div>
    </div>
  </div>
  <div v-else-if="message.kind === 'assistant'" class="row left">
    <div class="bubble assistant">
      <ToolCallCard v-for="tc in message.toolCalls" :key="tc.toolCallId" :toolCall="tc" />
      <StreamingText :content="message.content" :streaming="message.streaming" />
    </div>
  </div>
  <div v-else class="row center">
    <div class="bubble error">
      <strong>⚠ {{ message.code }}</strong>
      <div>{{ message.message }}</div>
    </div>
  </div>
</template>

<style scoped>
.row {
  display: flex;
  padding: 4px 12px;
  margin: 2px 0;
}
.right {
  justify-content: flex-end;
}
.left {
  justify-content: flex-start;
}
.center {
  justify-content: center;
}
.bubble {
  max-width: 85%;
  padding: 10px;
  border-radius: 12px;
}
.user {
  background: #3b82f6;
  color: white;
}
.assistant {
  background: #f3f4f6;
  color: #111;
}
.error {
  background: #fee2e2;
  color: #7f1d1d;
  border: 1px solid #ef4444;
}
.strip {
  display: flex;
  gap: 6px;
  flex-wrap: wrap;
  margin-bottom: 6px;
}
</style>

// clients/mobile-app/src/components/chat/MessageBubble.tsx
/**
 * MessageBubble — one row in the chat window. Routes to the right renderer
 * based on the message `kind`.
 */
import { StyleSheet, Text, View } from 'react-native';

import type { MessageItem } from '../../hooks/useChatStream';
import { StreamingText } from './StreamingText';
import { ToolCallCard } from './ToolCallCard';

type Props = {
  message: MessageItem;
};

export function MessageBubble({ message }: Props) {
  if (message.kind === 'user') {
    return (
      <View style={[styles.row, styles.userRow]}>
        <View style={[styles.bubble, styles.userBubble]}>
          <Text style={styles.userText}>{message.content}</Text>
        </View>
      </View>
    );
  }

  if (message.kind === 'assistant') {
    return (
      <View style={[styles.row, styles.assistantRow]}>
        <View style={[styles.bubble, styles.assistantBubble]}>
          {message.toolCalls.map((tc) => (
            <ToolCallCard key={tc.toolCallId} toolCall={tc} />
          ))}
          <StreamingText content={message.content} streaming={message.streaming} />
        </View>
      </View>
    );
  }

  // error
  return (
    <View style={[styles.row, styles.errorRow]}>
      <View style={[styles.bubble, styles.errorBubble]}>
        <Text style={styles.errorLabel}>⚠ {message.code}</Text>
        <Text style={styles.errorMessage}>{message.message}</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    marginVertical: 4,
    paddingHorizontal: 12,
  },
  userRow: { justifyContent: 'flex-end' },
  assistantRow: { justifyContent: 'flex-start' },
  errorRow: { justifyContent: 'center' },
  bubble: {
    maxWidth: '85%',
    borderRadius: 12,
    padding: 10,
  },
  userBubble: { backgroundColor: '#3b82f6' },
  assistantBubble: { backgroundColor: '#f3f4f6' },
  errorBubble: { backgroundColor: '#fee2e2', borderColor: '#ef4444', borderWidth: 1 },
  userText: { color: '#fff', fontSize: 16, lineHeight: 22 },
  errorLabel: { color: '#991b1b', fontWeight: '600', fontSize: 12, marginBottom: 4 },
  errorMessage: { color: '#7f1d1d', fontSize: 14, lineHeight: 20 },
});
